#Build
FROM node:24-alpine AS build
WORKDIR /next
COPY src ./src
COPY package.json .
COPY tsconfig.json .
COPY mui.d.ts .
COPY next.config.ts .
ARG ENCRYPTION_KEY
ARG COOKIE_ACCESS_TOKEN
ARG COOKIE_LANGUAGE_LOCALE
ARG COOKIE_SIDEBAR_EXPANDED
ARG DATA_URL
ARG NEXT_PUBLIC_DATA_URL
ENV ENCRYPTION_KEY=${ENCRYPTION_KEY}
ENV COOKIE_ACCESS_TOKEN=${COOKIE_ACCESS_TOKEN}
ENV COOKIE_LANGUAGE_LOCALE=${COOKIE_LANGUAGE_LOCALE}
ENV COOKIE_SIDEBAR_EXPANDED=${COOKIE_SIDEBAR_EXPANDED}
ENV DATA_URL=${NEXT_PUBLIC_DATA_URL}
ENV NEXT_PUBLIC_DATA_URL=${NEXT_PUBLIC_DATA_URL}
ENV NEXT_TELEMETRY_DISABLED 1
RUN npm install
RUN npm run build

#Start
FROM node:24-alpine AS start
WORKDIR /next
RUN addgroup --system --gid 3000 next
RUN adduser --system --uid 3000 next
USER next
COPY --from=build --chown=next:next /next/build/standalone ./
COPY --from=build --chown=next:next /next/build/static ./build/static
ARG ENCRYPTION_KEY
ARG COOKIE_ACCESS_TOKEN
ARG COOKIE_LANGUAGE_LOCALE
ARG COOKIE_SIDEBAR_EXPANDED
ARG DATA_URL
ARG NEXT_PUBLIC_DATA_URL
ENV ENCRYPTION_KEY=${ENCRYPTION_KEY}
ENV COOKIE_ACCESS_TOKEN=${COOKIE_ACCESS_TOKEN}
ENV COOKIE_LANGUAGE_LOCALE=${COOKIE_LANGUAGE_LOCALE}
ENV COOKIE_SIDEBAR_EXPANDED=${COOKIE_SIDEBAR_EXPANDED}
ENV DATA_URL=${DATA_URL}
ENV NEXT_PUBLIC_DATA_URL=${NEXT_PUBLIC_DATA_URL}
ENV NEXT_TELEMETRY_DISABLED 1
CMD ["node", "server.js"]